name: opal
description: "Another UI Framework"
version: 0.0.1
homepage:
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  mesh_gradient: ^1.3.4
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  tinycolor2: ^3.0.1
  toxic: ^1.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  shaders:
    - shader/opal.frag
